"""
Pitch Processor for Karaoke Builder

Stage 3: Pitch Contour Analysis
Uses torchcrepe to extract continuous pitch contour from vocals
"""

import json
from pathlib import Path
from typing import List, Dict, Any

from .base_processor import BaseProcessor, ProcessorContext
from ..stage_runner import StageResult
from ..debug_logger import debug_logger
from ..config import PITCH_MODEL, PITCH_TIMEOUT, SAMPLE_RATE, HOP_LENGTH


class PitchProcessor(BaseProcessor):
    """Processor for pitch contour extraction using torchcrepe"""
    
    @property
    def name(self) -> str:
        return "Pitch"
    
    def execute(self) -> StageResult:
        """
        Execute pitch contour extraction
        
        Returns:
            StageResult with pitch.json path containing pitch data
        """
        from ..stage_runner import StageRunner
        
        # Validate input
        error = self.validate_inputs([self.context.vocals_file])
        if error:
            debug_logger.log_error(self.name, error)
            return StageResult(
                success=False,
                stage=self.name,
                duration=0,
                outputs=[],
                stdout="",
                stderr=error,
                exit_code=-1,
                error_message=error
            )
        
        # Create output directory
        pitch_dir = self.create_subdirectory("pitch")
        pitch_file = pitch_dir / "pitch.json"
        
        # Build Python script for torchcrepe processing
        script_content = self._build_pitch_script(
            vocals_path=str(self.context.vocals_file),
            output_path=str(pitch_file),
            model=PITCH_MODEL,
            sample_rate=SAMPLE_RATE,
            hop_length=HOP_LENGTH
        )
        
        script_file = pitch_dir / "run_pitch.py"
        with open(script_file, 'w', encoding='utf-8') as f:
            f.write(script_content)
        
        # Build command
        command = ["python", str(script_file)]
        
        debug_logger.log_info(self.name, f"Using model: {PITCH_MODEL}")
        debug_logger.log_info(self.name, f"Sample rate: {SAMPLE_RATE} Hz")
        debug_logger.log_info(self.name, f"Output: {pitch_file.name}")
        
        # Run pitch extraction
        runner = StageRunner(self.context.job_id, self.work_dir)
        result = runner.run(
            name=self.name,
            command=command,
            input_files=[self.context.vocals_file],
            output_files=[pitch_file],
            timeout=PITCH_TIMEOUT,
        )
        
        # Update context on success
        if result.success:
            self.context.pitch_json = pitch_file
            
            # Read and log statistics
            try:
                with open(pitch_file, 'r', encoding='utf-8') as f:
                    pitch_data = json.load(f)
                
                points = pitch_data.get("points", [])
                voiced_points = [p for p in points if p.get("confidence", 0) > 0.5]
                
                debug_logger.log_info(
                    self.name, 
                    f"Pitch points: {len(points)} total, {len(voiced_points)} voiced"
                )
                
                if points:
                    freqs = [p["frequency"] for p in voiced_points if p["frequency"] > 0]
                    if freqs:
                        min_freq = min(freqs)
                        max_freq = max(freqs)
                        avg_freq = sum(freqs) / len(freqs)
                        debug_logger.log_info(
                            self.name,
                            f"Frequency range: {min_freq:.1f} - {max_freq:.1f} Hz (avg: {avg_freq:.1f} Hz)"
                        )
                        
            except Exception as e:
                debug_logger.log_warning(self.name, f"Could not read pitch statistics: {e}")
        
        return result
    
    def _build_pitch_script(self, vocals_path: str, output_path: str,
                            model: str, sample_rate: int, hop_length: int) -> str:
        """Build Python script for torchcrepe processing"""
        
        return f'''#!/usr/bin/env python3
"""
Pitch Contour Extraction Script
Generated by Karaoke Builder
"""

import sys
import json
import warnings
warnings.filterwarnings("ignore")

try:
    import torch
    import torchcrepe
    import torchaudio
except ImportError as e:
    print(f"ERROR: Required library not found: {{e}}", file=sys.stderr)
    print("Please install: pip install torchcrepe torchaudio", file=sys.stderr)
    sys.exit(1)

# Configuration
VOCALS_PATH = r"{vocals_path}"
OUTPUT_PATH = r"{output_path}"
MODEL_NAME = "{model}"
SAMPLE_RATE = {sample_rate}
HOP_LENGTH = {hop_length}

def main():
    print(f"Loading audio: {{VOCALS_PATH}}")
    
    try:
        # Load audio
        waveform, sr = torchaudio.load(VOCALS_PATH)
        
        # Convert to mono if stereo
        if waveform.shape[0] > 1:
            waveform = waveform.mean(dim=0, keepdim=True)
        
        # Resample if needed
        if sr != SAMPLE_RATE:
            resampler = torchaudio.transforms.Resample(sr, SAMPLE_RATE)
            waveform = resampler(waveform)
        
        print(f"Audio shape: {{waveform.shape}}, Sample rate: {{SAMPLE_RATE}} Hz")
        
        # Detect device
        device = "cuda" if torch.cuda.is_available() else "cpu"
        print(f"Using device: {{device}}")
        
        # Extract pitch using torchcrepe
        print(f"Extracting pitch with model: {{MODEL_NAME}}")
        
        # torchcrepe expects specific parameters
        # frequency_bin: time x 1
        # periodicity: time x 1
        
        pitch_result = torchcrepe.predict(
            waveform,
            SAMPLE_RATE,
            HOP_LENGTH,
            fmin=50.0,      # Minimum frequency (Hz)
            fmax=1000.0,    # Maximum frequency (Hz)
            model=MODEL_NAME,
            batch_size=512,
            device=device,
            return_periodicity=True
        )
        
        frequency, periodicity = pitch_result
        
        # Convert to our format
        print("Converting to normalized format...")
        
        # Calculate time points
        num_frames = frequency.shape[1]
        time_step = HOP_LENGTH / SAMPLE_RATE
        
        points = []
        for i in range(num_frames):
            time_sec = i * time_step
            freq_val = float(frequency[0, i].item())
            conf_val = float(periodicity[0, i].item())
            
            # Filter out low-confidence points
            # But keep them in the output for completeness
            points.append({{
                "time": round(time_sec, 3),
                "frequency": round(freq_val, 2),
                "confidence": round(conf_val, 4)
            }})
        
        # Build output structure
        output = {{
            "format": "torchcrepe_pitch",
            "version": 1,
            "metadata": {{
                "sample_rate": SAMPLE_RATE,
                "hop_length": HOP_LENGTH,
                "model": MODEL_NAME,
                "duration": round(num_frames * time_step, 2)
            }},
            "points": points
        }}
        
        # Save output
        print(f"Saving to {{OUTPUT_PATH}}")
        with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
            json.dump(output, f, ensure_ascii=False, indent=2)
        
        # Statistics
        voiced_points = [p for p in points if p["confidence"] > 0.5]
        print(f"Total points: {{len(points)}}")
        print(f"Voiced points: {{len(voiced_points)}} ({{100*len(voiced_points)/len(points):.1f}}%)")
        
        if voiced_points:
            freqs = [p["frequency"] for p in voiced_points if p["frequency"] > 0]
            if freqs:
                print(f"Frequency range: {{min(freqs):.1f}} - {{max(freqs):.1f}} Hz")
        
        print("Success!")
        
    except Exception as e:
        print(f"ERROR: {{str(e)}}", file=sys.stderr)
        import traceback
        traceback.print_exc(file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
'''
